# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r echo = TRUE}
data<-read.csv("data/activity.csv")
```

## What is mean total number of steps taken per day?

```{r echo = TRUE}
totalStepsByDate<-aggregate(steps ~ date, data, sum,na.rm=T)
hist(totalStepsByDate$steps)

mean(totalStepsByDate$steps, na.rm=T)
median(totalStepsByDate$steps, na.rm=T)

```


## What is the average daily activity pattern?
```{r echo = TRUE}
meanStepsByInterval<-aggregate(steps ~ interval, data, mean,na.rm=T)
plot(meanStepsByInterval$interval,meanStepsByInterval$steps)
meanStepsByInterval[which.max( meanStepsByInterval[,2] ),]
```

## Imputing missing values
```{r echo = TRUE}
nrow(data) - sum(complete.cases(data))
dataNoNAs <- data
for (i in 1:nrow(dataNoNAs))
{
  if(is.na(dataNoNAs[i,1]))
  {
    dataNoNAs[i,1]<-meanStepsByInterval[meanStepsByInterval$interval == dataNoNAs[i,3],2]
  }
}
nrow(data[is.na(data$steps),])
nrow(dataNoNAs[is.na(dataNoNas$steps),])

totalStepsByDateNoNAs<-aggregate(steps ~ date, dataNoNAs, sum,na.rm=T)
hist(totalStepsByDateNoNAs$steps)

mean(totalStepsByDateNoNAs$steps, na.rm=T)
median(totalStepsByDateNoNAs$steps, na.rm=T)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r echo = TRUE}
dayType <-apply(dataNoNAs,1,function(row) 
  {
    if(weekdays(as.Date(row[2],"%Y-%m-%d"))=="Sunday" ||
         weekdays(as.Date(row[2],"%Y-%m-%d"))=="Saturday")
      { "weekend" }
   else
      { "weekday" }
   })
dataNoNAs<-data.frame(dataNoNAs,dayType)
head(dataNoNAs)
```


```{r echo =TRUE}
meanStepsByIntervalDayFactor<-aggregate(steps ~ interval+dayType, dataNoNAs, mean,na.rm=T)
tst1<-meanStepsByIntervalDayFactor[meanStepsByIntervalDayFactor$dayType=="weekday",]
tst2<-meanStepsByIntervalDayFactor[meanStepsByIntervalDayFactor$dayType=="weekend",]
plot(tst1$interval,tst1$steps)
plot(tst2$interval,tst2$steps)
```